### ISSUE TITLE
Syntax detection does not work on Windows

### ISSUE THREAD

**Issue by FichteFoll** [osoco/sublimetext-grails#17]
At the request of https://forum.sublimetext.com/t/how-do-you-use-a-package-like-grails/16690 I took a look into the source and it appears that you are checking for forward slashes in the file path in order to set the approproate syntax (and activate completions etc.). `view.file_path` returns paths with backslashes on Windows.

You might also want to add a "Usage" section to your readme explaining how this package works.

**Comment by gcrick** [comment]
Oops! Thank you, I'll look into it as soon as I get a chance. 

I'll also see what I can do to make the README a bit clearer.

**Comment by gcrick** [comment]
I wasn't able to find any documentation about view.file_path, but I think I found an alternative that works for Windows too. The latest release should fix the problem. I also added a "Usage" section to the documentation as suggested.

Thanks again!
