### ISSUE TITLE
Need more examples

### ISSUE THREAD

**Issue by Alexey-T** [osoco/sublimetext-grails#19]
Repo has the .gsp example.
Good.
Can you please, also put the

- Grails file example 
- GrailsDoc example 

?

**Comment by gcrick** [comment]
I'm sorry to say that we have not used Sublime with Grails for some time and this project has not had any active development. It has not been updated to the latest versions so I don't think it would be very useful to add example files that are outdated. Perhaps you could take a look at some of the forks to see if someone else has continued development.
